name: voltage_hub
version: 1.0.0
config-version: 2

profile: voltage_hub

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  voltage_hub:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +schema: "{{ env_var('BQ_DATASET_STAGING_SAMPLE', 'staging_sample') if target.name == 'sample' else env_var('BQ_DATASET_STAGING', 'staging') }}"
    marts:
      +schema: "{{ env_var('BQ_DATASET_MARTS_SAMPLE', 'marts_sample') if target.name == 'sample' else env_var('BQ_DATASET_MARTS', 'marts') }}"
